

export const MOVIES_REQUEST = "MOVIES_REQUEST";
export const MOVIES_SUCCESS = "MOVIES_SUCCESS";
export const MOVIES_FAILURE = "MOVIES_FAILURE";

export const MOVIES_ADD = 'MOVIES_ADD'

export const MOVIES_UPDATE = 'MOVIES_UPDATE'